#!/bin/sh

source "$CONFIG_DIR/colors.sh" # Loads all defined colors

# This is a demo config to showcase some of the most important commands.
# It is meant to be changed and configured, as it is intentionally kept sparse.
# For a (much) more advanced configuration example see my dotfiles:
# https://github.com/FelixKratz/dotfiles

PLUGIN_DIR="$CONFIG_DIR/plugins"
ITEM_DIR="$CONFIG_DIR/items"

##### Bar Appearance #####
# Configuring the general appearance of the bar.
# These are only some of the options available. For all options see:
# https://felixkratz.github.io/SketchyBar/config/bar
# If you are looking for other colors, see the color picker:
# https://felixkratz.github.io/SketchyBar/config/tricks#color-picker

sketchybar --bar  position=top      \
                  height=34         \
                  display=main      \
                  blur_radius=30    \
                  color=$BAR_COLOR  \
                  padding_left=8    \
                  padding_right=8   \

##### Changing Defaults #####
# We now change some default values, which are applied to all further items.
# For a full list of all available item properties see:
# https://felixkratz.github.io/SketchyBar/config/items

default=(
    padding_left=5
    padding_right=5
    icon.font="JetBrainsMonoNL Nerd Font:Medium:14.5"
    label.font="JetBrainsMonoNL Nerd Font:Regular:14.0"
    icon.color=$WHITE
    label.color=$WHITE
    icon.padding_left=10
    icon.padding_right=4
    label.padding_left=4
    label.padding_right=10
    background.color=$ITEM_BG_COLOR
    background.corner_radius=6
    background.height=28
)

sketchybar --default "${default[@]}"

# Left Side Items
# source $ITEM_DIR/spaces.sh
sketchybar -m --add item logo left      \
              --set logo icon=         \
              --set logo icon.padding_right=-4 \
                    click_script="sketchybar -m --update"

source $ITEM_DIR/front_app.sh

# Right Side Items
source $ITEM_DIR/calendar.sh
# source $ITEM_DIR/keyboard.sh
source $ITEM_DIR/volume.sh
source $ITEM_DIR/battery.sh
source $ITEM_DIR/cpu.sh

sketchybar --update
